#!/bin/sh

rm -rf /home/infoscreen/.mozilla /home/infoscreen/.cache

matchbox-window-manager -use_titlebar no -use_cursor no &

# disable screen saver
xset s off

# disable screen blanking
xset s noblank

# disable VESA display power management signaling
xset -dpms


while true; do
    cd /opt/infoscreen
      ./sbin/run.py
        sleep 0.1
      done
done

