#!/usr/bin/env bash

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!USE THIS SCRIPT ONLY FOR TESTING!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# fail on any error (i.e. ret != 0)
set -e

# redirect stdout, stderr to file
exec &> >(tee ../init.log)

# error handling
function fail() {
  printf "%s" "FAILING: ${1}" | logger
  pkill X
} ; trap 'fail "bash ERR"' ERR


X -nocursor &

# wait for X finish initialization
sleep 60

# disable screen saver
xset s off

# disable screen blanking
xset s noblank

# disable VESA display power management signaling
xset -dpms
